#!/usr/bin/env ruby

folder = File.expand_path(File.dirname(__FILE__))
require_relative "#{folder}/../../../../libs/ruby/base-runner"

class Runner
  include BaseRunner

  def run
    on_path "s3cmd"
    on_path "cs-api-assets"
    has_folder "~/cs-api-assets"
    target_bucket = env_var "ENV_AMAZON_ASSETS_BUCKET"
    live_bucket = env_var "CORESPRING_LIVE_ASSETS_BUCKET"
    ch_dir "~/cs-api-assets"
    run_cmd "cs-api-assets pull-bucket #{live_bucket}"
    run_cmd "cs-api-assets push-bucket #{live_bucket} --remote-bucket=#{target_bucket}"
  end
end


Runner.new.run
