#!/usr/bin/env ruby
require_relative '../../../../libs/ruby'
include Utils

# See: github.com/corespring/mongo-migrator for more information
jar = env_var "MIGRATIONS_JAR"
migrations_path = env_var "MIGRATIONS_PATH"
mongo_uri = env_var "ENV_MONGO_URI"
replica_set_name = env_var "ENV_MONGO_REPLICA_SET_NAME", false
uri = get_migrator_uri(mongo_uri, replica_set_name)
run_cmd "java -jar #{jar} migrate #{commit_hash} \"#{uri}\" #{migrations_path}"
