#!/usr/bin/env ruby
folder = File.expand_path(File.dirname(__FILE__))
p = "#{folder}/../../../../libs/ruby/"
require_relative "#{p}/restore-db-from-s3"
require_relative "#{p}/run-migrations"
require_relative "#{p}/copy-s3-assets"
require_relative "#{p}/commit-hash"
require_relative "#{p}/flush-cache"

FlushCache.new.run
#RestoreDbFromS3.new.run
commit_hash = CommitHash.new.get("APP_PATH", "develop")
RunMigrations.new.run(commit_hash)
#CopyS3Assets.new.run
